function AudWMimportExcel(path)
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\OBS_Rm\Documents\Task_AudWM-main\data\fr_20241002-141854.csv
%
% Auto-generated by MATLAB on 02-Oct-2024 14:51:13

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 11);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["TrialNumber", "Participant", "Response", "ResponsePeriodOnset", "RT", "Seed", "CueFrequency", "CueFrequencyRange", "ChoiceFrequency", "ChoiceFrequencyRange", "Coherence"];
opts.VariableTypes = ["double", "categorical", "categorical", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Participant", "Response"], "EmptyFieldRule", "auto");

% Import the data
tbl = readtable(path, opts);

%% Convert to output type
TrialNumber = tbl.TrialNumber;
Participant = tbl.Participant;
Response = tbl.Response;
ResponsePeriodOnset = tbl.ResponsePeriodOnset;
RT = tbl.RT;
Seed = tbl.Seed;
CueFrequency = tbl.CueFrequency;
CueFrequencyRange = tbl.CueFrequencyRange;
ChoiceFrequency = tbl.ChoiceFrequency;
ChoiceFrequencyRange = tbl.ChoiceFrequencyRange;
Coherence = tbl.Coherence;

%% Clear temporary variables
clear opts tbl
end